import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Poppins, Inter } from "next/font/google";
import { NavbarDemo } from "./components/Navbar";
import { Fredoka } from 'next/font/google';
// const fredoka = Fredoka({ weight: '400', subsets: ['latin'] , variable: "--font-Fredroka_one", });

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-inter",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased `}
      >
        <NavbarDemo />
        <div className="overflow-x-clip max-h-screen">
        {children}
        </div>
      </body>
    </html>
  );
}
